name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  linux-release:
    name: Linux Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@master
        with:
          command: build
          arguments: --release --target x86_64-unknown-linux-gnu
          use-cross: true

  macos-release:
    name: macOS Release
    needs: [test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@master
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@master
        with:
          command: build
          arguments: --release --target x86_64-apple-darwin 
          use-cross: true
