name: Release
on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  release:
    name: Release
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: hecrj/setup-rust-action@master
      - uses: actions/checkout@master
      - name: Install cross
        run: | # Install cross from master until fix for TTY is released
          git clone https://github.com/rust-embedded/cross
          cargo install --force --path ./cross

        # Build the release for the platform on the appropriate runner
      - run: |
          mkdir x86_64-unknown-linux-gnu
          cross build --target x86_64-unknown-linux-gnu --release
          cp target/x86_64-unknown-linux-gnu/release/starship x86_64-unknown-linux-gnu
          tar -czf x86_64-unknown-linux-gnu
        if: runner.os == 'Linux'
      - name: Release (Linux)
        uses: softprops/action-gh-release@v0.1.0
        if: runner.os == 'Linux'
        with: 
          files: x86_64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          mkdir x86_64-apple-darwin
          cross build --target x86_64-apple-darwin --release
          cp target/x86_64-unknown-linux-gnu/release/starship x86_64-apple-darwin
          tar -czf x86_64-apple-darwin
        if: runner.os == 'macOS'
      - name: Release (macOS)
        uses: softprops/action-gh-release@v0.1.0
        if: runner.os == 'macOS'
        with: 
          files: x86_64-apple-darwin.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
