name: Release
on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  release:
    name: Release
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: hecrj/setup-rust-action@master
      - uses: actions/checkout@master
      - run: cargo install cross
      - run: cross build --target x86_64-unknown-linux-gnu --release
        if: ${{ matrix.os }} == 'ubuntu-latest'
      - run: cross build --target x86_64-apple-darwin --release
        if: ${{ matrix.os }} == 'macOS-latest'
